1089-134686-0000	he hoped there would be stew for dinner turnips and carrots and bruised potatoes and fat mutton pieces to be ladled out in thick peppered flour fattened sauce
1089-134686-0001	stuff it into you his belly counseled him
1089-134686-0002	after early nightfall the yellow lamps would light up here and there the squalid quarter of the brothels
1089-134686-0003	hello bertie any good in your mind
1089-134686-0004	number 10 fresh nelly is waiting on you good night husband
1089-134686-0005	the music came nearer and he recalled the words the words of shelley is fragment upon the moon wandering companionless pale for weariness
1089-134686-0006	the dull light fell more faintly upon the page whereon another equation began to unfold itself slowly and to spread abroad its widening tail
1089-134686-0007	a cold lucid indifference reigned in his soul
1089-134686-0008	the chaos in which his ardor extinguished itself was a cold indifferent knowledge of himself
1089-134686-0009	at most by an alms given to a beggar whose blessing he fled from he might hope wearily to win for himself some measure of actual grace
1089-134686-0010	well now ennis i declare you have a head and so has my stick
1089-134686-0011	on saturday mornings when the sodality met in the chapel to recite the little office his place was a cushioned kneeling desk at the right of the altar from which he led his wing of boys through the responses
1089-134686-0012	her eyes seemed to regard him with mild pity her holiness a strange light glowing faintly upon her frail flesh did not humiliate the sinner who approached her
1089-134686-0013	if ever he was impelled to cast sin from him and to repent the impulse that moved him was the wish to be her knight
1089-134686-0014	he tried to think how it could be
1089-134686-0015	but the dusk deepening in the schoolroom covered over his thoughts the bell rang
1089-134686-0016	then you can ask him questions on the catechism dedalus
1089-134686-0017	stephen leaning back and drawing idly on his scribbler listened to the talk about him which heron checked from time to time by saying
1089-134686-0018	it was strange too that he found an arid pleasure in following up to the end the rigid lines of the doctrines of the church and penetrating into obscure silences only to hear and feel the more deeply his own condemnation
1089-134686-0019	the sentence of saint james which says that he who offends against one commandment becomes guilty of all had seemed to him 1st a swollen phrase until he had begun to grope in the darkness of his own state
1089-134686-0020	if a man had stolen a pound in his youth and had used that pound to amass a huge fortune how much was he obliged to give back the pound he had stolen only or the pound together with the compound interest accruing upon it or all his huge fortune
1089-134686-0021	if a layman in giving baptism pour the water before saying the words is the child baptized
1089-134686-0022	how comes it that while the 1st beatitude promises the kingdom of heaven to the poor of heart the 2nd beatitude promises also to the meek that they shall possess the land
1089-134686-0023	why was the sacrament of the eucharist instituted under the 2 species of bread and wine if jesus christ be present body and blood soul and divinity in the bread alone and in the wine alone
1089-134686-0024	if the wine change into vinegar and the host crumble into corruption after they have been consecrated is jesus christ still present under their species as god and as man
1089-134686-0025	a gentle kick from the tall boy in the bench behind urged stephen to ask a difficult question
1089-134686-0026	the rector did not ask for a catechism to hear the lesson from
1089-134686-0027	he clasped his hands on the desk and said
1089-134686-0028	the retreat will begin on wednesday afternoon in honor of saint francis xavier whose feast day is saturday
1089-134686-0029	on friday confession will be heard all the afternoon after beads
1089-134686-0030	beware of making that mistake
1089-134686-0031	stephen is heart began slowly to fold and fade with fear like a withering flower
1089-134686-0032	he is called as you know the apostle of the indies
1089-134686-0033	a great saint saint francis xavier
1089-134686-0034	the rector paused and then shaking his clasped hands before him went on
1089-134686-0035	he had the faith in him that moves mountains
1089-134686-0036	a great saint saint francis xavier
1089-134686-0037	in the silence their dark fire kindled the dusk into a tawny glow
1089-134691-0000	he could wait no longer
1089-134691-0001	for a full hour he had paced up and down waiting but he could wait no longer
1089-134691-0002	he set off abruptly for the bull walking rapidly lest his father is shrill whistle might call him back and in a few moments he had rounded the curve at the police barrack and was safe
1089-134691-0003	the university
1089-134691-0004	pride after satisfaction uplifted him like long slow waves
1089-134691-0005	whose feet are as the feet of harts and underneath the everlasting arms
1089-134691-0006	the pride of that dim image brought back to his mind the dignity of the office he had refused
1089-134691-0007	soon the whole bridge was trembling and resounding
1089-134691-0008	the uncouth faces passed him 2 by 2 stained yellow or red or livid by the sea and as he strove to look at them with ease and indifference a faint stain of personal shame and commiseration rose to his own face
1089-134691-0009	angry with himself he tried to hide his face from their eyes by gazing down sideways into the shallow swirling water under the bridge but he still saw a reflection therein of their top heavy silk hats and humble tape like collars and loosely hanging clerical clothes brother hickey
1089-134691-0010	brother mac ardle brother keogh
1089-134691-0011	their piety would be like their names like their faces like their clothes and it was idle for him to tell himself that their humble and contrite hearts it might be paid a far richer tribute of devotion than his had ever been a gift tenfold more acceptable than his elaborate adoration
1089-134691-0012	it was idle for him to move himself to be generous towards them to tell himself that if he ever came to their gates stripped of his pride beaten and in beggar is weeds that they would be generous towards him loving him as themselves
1089-134691-0013	idle and embittering finally to argue against his own dispassionate certitude that the commandment of love bade us not to love our neighbor as ourselves with the same amount and intensity of love but to love him as ourselves with the same kind of love
1089-134691-0014	the phrase and the day and the scene harmonized in a chord
1089-134691-0015	words was it their colors
1089-134691-0016	they were voyaging across the deserts of the sky a host of nomads on the march voyaging high over ireland westward bound
1089-134691-0017	the europe they had come from lay out there beyond the irish sea europe of strange tongues and valleyed and woodbegirt and citadelled and of entrenched and marshaled races
