1089-134686-0000	he hoped there would be stew for dinner turnips and carrots and bruised potatoes and fat mutton pieces to be ladled out in thick peppered flour fattened sauce
1089-134686-0001	stuff it into you his belly counseled him
1089-134686-0002	after early nightfall the yellow lamps would light up here and there the squalid quarter of the brothels
1089-134686-0003	hello bertie any good in your mind
1089-134686-0004	number 10 fresh nelly is waiting on you good night husband
1089-134686-0005	the music came nearer and he recalled the words the words of shelley is fragment upon the moon wandering companionless pale for weariness
1089-134686-0006	the dull light fell more faintly upon the page whereon another equation began to unfold itself slowly and to spread abroad its widening tail
1089-134686-0007	a cold lucid indifference reigned in his soul
1089-134686-0008	the chaos in which his ardor extinguished itself was a cold indifferent knowledge of himself
1089-134686-0009	at most by an alms given to a beggar whose blessing he fled from he might hope wearily to win for himself some measure of actual grace
1089-134686-0010	well now ennis i declare you have a head and so has my stick
1089-134686-0011	on saturday mornings when the sodality met in the chapel to recite the little office his place was a cushioned kneeling desk at the right of the altar from which he led his wing of boys through the responses
1089-134686-0012	her eyes seemed to regard him with mild pity her holiness a strange light glowing faintly upon her frail flesh did not humiliate the sinner who approached her
1089-134686-0013	if ever he was impelled to cast sin from him and to repent the impulse that moved him was the wish to be her knight
1089-134686-0014	he tried to think how it could be
1089-134686-0015	but the dusk deepening in the schoolroom covered over his thoughts the bell rang
1089-134686-0016	then you can ask him questions on the catechism daedalus
1089-134686-0017	stephen leaning back and drawing idly on his scribbler listened to the talk about him which heron checked from time to time by saying
1089-134686-0018	it was strange too that he found an arid pleasure in following up to the end the rigid lines of the doctrines of the church and penetrating into obscure silences only to hear and feel the more deeply his own condemnation
1089-134686-0019	the sentence of saint james which says that he who offends against one commandment becomes guilty of all had seemed to him 1st a swollen phrase until he had begun to grope in the darkness of his own state
1089-134686-0020	if a man had stolen a pound in his youth and had used that pound to amass a huge fortune how much was he obliged to give back the pound he had stolen only or the pound together with the compound interest accruing upon it or all his huge fortune
1089-134686-0021	if a layman in giving baptism pour the water before saying the words is the child baptized
1089-134686-0022	how comes it that while the 1st beatitude promises the kingdom of heaven to the poor of heart the 2nd beatitude promises also to the meek that they shall possess the land
1089-134686-0023	why was the sacrament of the eucharist instituted under the 2 species of bread and wine if jesus christ be present body and blood soul and divinity in the bread alone and in the wine alone
1089-134686-0024	if the wine change into vinegar and the host crumble into corruption after they have been consecrated is jesus christ still present under their species as god and as man
1089-134686-0025	a gentle kick from the tall boy in the bench behind urged stephen to ask a difficult question
1089-134686-0026	the rector did not ask for a catechism to hear the lesson from
1089-134686-0027	he clasped his hands on the desk and said
1089-134686-0028	the retreat will begin on wednesday afternoon in honor of saint francis xavier whose feast day is saturday
1089-134686-0029	on friday confession will be heard all the afternoon after beads
1089-134686-0030	beware of making that mistake
1089-134686-0031	stephen is heart began slowly to fold and fade with fear like a withering flower
